version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB.URI=mongodb://localhost:27017/volumes
  mongo_db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: